# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [4]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Collecting pandas
  Downloading pandas-3.0.6-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy
  Downloading numpy-2.5.3-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 36.0 MB/s  0:00:006m0:00:01
Downloading numpy-2.5.3-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 36.0 MB/s  0:00:006m0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.5.3 pandas-3.0.6
Note: you may need to restart the kernel to use updated packages.

In [7]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [10]:
# Load the Food choices data set.

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [11]:
# Count by hand. (lol kidding)
df_food.shape

(125, 61)

In [16]:
# Try to print or display it nicely.

df_food.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
5,2.25,1,1,610,3.0,980.0,2,"Candy, brownies and soda.","None, i don't eat comfort food. I just eat whe...",4.0,...,1.0,2.0,4,940.0,345,None.,1,2,1315,190
6,3.8,2,1,610,3.0,420.0,2,"Chocolate, ice cream, french fries, pretzels","stress, boredom",1.0,...,1.0,1.0,5,940.0,690,soccer,4,1,1315,180
7,3.3,1,1,720,3.0,420.0,1,"Ice cream, cheeseburgers, chips.",I eat comfort food when im stressed out from s...,1.0,...,1.0,2.0,1,725.0,500,none,4,2,1315,137
8,3.3,1,1,430,NaN,420.0,1,"Donuts, ice cream, chips",Boredom,2.0,...,2.0,2.0,5,725.0,345,none,3,2,760,180
9,3.3,1,1,430,3.0,315.0,2,"Mac and cheese, chocolate, and pasta","Stress, anger and sadness",1.0,...,1.0,1.0,4,580.0,345,field hockey,5,1,900,125

What are the columns and their types in this data set?

In [17]:
# Show the column names and their types.

df_food.dtypes

GPA                     str
Gender                int64
breakfast             int64
calories_chicken      int64
calories_day        float64
                     ...
type_sports             str
veggies_day           int64
vitamins              int64
waffle_calories       int64
weight                  str
Length: 61, dtype: object

In [19]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.

df_food.dtypes.to_frame()

                                    0
GPA                               str
Gender                          int64
breakfast                       int64
calories_chicken                int64
calories_day                  float64
calories_scone                float64
coffee                          int64
comfort_food                      str
comfort_food_reasons              str
comfort_food_reasons_coded    float64
cook                          float64
comfort_food_reasons_coded.1    int64
cuisine                       float64
diet_current                      str
diet_current_coded              int64
drink                         float64
eating_changes                    str
eating_changes_coded            int64
eating_changes_coded1           int64
eating_out                      int64
employment                    float64
ethnic_food                     int64
exercise                      float64
father_education              float64
father_profession                 str
fav_cuisine                       str
fav_cuisine_coded               int64
fav_food                      float64
food_childhood                    str
fries                           int64
fruit_day                       int64
grade_level                     int64
greek_food                      int64
healthy_feeling                 int64
healthy_meal                      str
ideal_diet                        str
ideal_diet_coded                int64
income                        float64
indian_food                     int64
italian_food                    int64
life_rewarding                float64
marital_status                float64
meals_dinner_friend               str
mother_education              float64
mother_profession                 str
nutritional_check               int64
on_off_campus                 float64
parents_cook                    int64
pay_meal_out                    int64
persian_food                  float64
self_perception_weight        float64
soup                          float64
sports                        float64
thai_food                       int64
tortilla_calories             float64
turkey_calories                 int64
type_sports                       str
veggies_day                     int64
vitamins                        int64
waffle_calories                 int64
weight                            str

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [26]:
# Remove ‘em.
df_food_col_subset = df_food[["calories_day", "weight", "Gender"]]
df_food_col_subset

     calories_day                    weight  Gender
0             NaN                       187       2
1             3.0                       155       1
2             4.0  I'm not answering this.        1
3             3.0             Not sure, 240       1
4             2.0                       190       1
..            ...                       ...     ...
120           4.0                       156       1
121           2.0                       180       1
122           NaN                       120       1
123           4.0                       135       2
124           NaN                       135       1

[125 rows x 3 columns]

In [28]:
# Is there a second way to remove columns?

df_food_col_subset_2 = df_food.drop(columns=["calories_day", "weight", "Gender"])
df_food_col_subset_2

,GPA,breakfast,calories_chicken,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,cook,comfort_food_reasons_coded.1,...,self_perception_weight,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories
0,2.4,1,430,315.0,1,none,we dont have comfort,9.0,2.0,9,...,3.0,1.0,1.0,1,1165.0,345,car racing,5,1,1315
1,3.654,1,610,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,3.0,1,...,3.0,1.0,1.0,2,725.0,690,Basketball,4,2,900
2,3.3,1,720,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,1.0,1,...,6.0,1.0,2.0,5,1165.0,500,none,5,1,900
3,3.2,1,430,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,2.0,2,...,5.0,1.0,2.0,5,725.0,690,NaN,3,1,1315
4,3.5,1,720,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,1.0,1,...,4.0,1.0,1.0,4,940.0,500,Softball,4,2,760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,3.5,1,610,420.0,2,"wine. mac and cheese, pizza, ice cream",boredom and sadness,NaN,3.0,2,...,4.0,1.0,1.0,5,940.0,500,Softball,5,1,1315
121,3,1,265,315.0,2,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,NaN,3.0,3,...,4.0,1.0,NaN,4,940.0,500,basketball,5,2,1315
122,3.882,1,720,420.0,1,"rice, potato, seaweed soup",sadness,NaN,3.0,3,...,4.0,1.0,2.0,5,580.0,690,none,4,2,1315
123,3,1,720,420.0,1,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",NaN,3.0,7,...,2.0,2.0,2.0,1,940.0,500,NaN,3,1,1315
124,3.9,1,430,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",NaN,NaN,5,...,3.0,1.0,2.0,2,725.0,345,NaN,4,2,575

In [30]:
# 🚀 Extra credit: What about a third way to remove columns?
df_food_col_subset_3 = df_food.loc[:, ~df_food.columns.isin(["calories_day", "weight", "Gender"])]
df_food_col_subset_3

,GPA,breakfast,calories_chicken,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,cook,comfort_food_reasons_coded.1,...,self_perception_weight,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories
0,2.4,1,430,315.0,1,none,we dont have comfort,9.0,2.0,9,...,3.0,1.0,1.0,1,1165.0,345,car racing,5,1,1315
1,3.654,1,610,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,3.0,1,...,3.0,1.0,1.0,2,725.0,690,Basketball,4,2,900
2,3.3,1,720,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,1.0,1,...,6.0,1.0,2.0,5,1165.0,500,none,5,1,900
3,3.2,1,430,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,2.0,2,...,5.0,1.0,2.0,5,725.0,690,NaN,3,1,1315
4,3.5,1,720,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,1.0,1,...,4.0,1.0,1.0,4,940.0,500,Softball,4,2,760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,3.5,1,610,420.0,2,"wine. mac and cheese, pizza, ice cream",boredom and sadness,NaN,3.0,2,...,4.0,1.0,1.0,5,940.0,500,Softball,5,1,1315
121,3,1,265,315.0,2,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,NaN,3.0,3,...,4.0,1.0,NaN,4,940.0,500,basketball,5,2,1315
122,3.882,1,720,420.0,1,"rice, potato, seaweed soup",sadness,NaN,3.0,3,...,4.0,1.0,2.0,5,580.0,690,none,4,2,1315
123,3,1,720,420.0,1,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",NaN,3.0,7,...,2.0,2.0,2.0,1,940.0,500,NaN,3,1,1315
124,3.9,1,430,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",NaN,NaN,5,...,3.0,1.0,2.0,2,725.0,345,NaN,4,2,575

What about `NaN`s? How many are there?

In [31]:
# Count ‘em.

df_food_col_subset.isna()

     calories_day  weight  Gender
0            True   False   False
1           False   False   False
2           False   False   False
3           False   False   False
4           False   False   False
..            ...     ...     ...
120         False   False   False
121         False   False   False
122          True   False   False
123         False   False   False
124          True   False   False

[125 rows x 3 columns]

In [32]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.

df_food_col_subset.isna().sum().to_frame()

               0
calories_day  19
weight         2
Gender         0

In [33]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.

df_food_col_subset \
    .isna() \
    .sum() \
    .to_frame()

               0
calories_day  19
weight         2
Gender         0

We gotta remove those `NaN`s―the entire row.

In [35]:
# Drop ‘em in-place.

df_food_col_subset.dropna(inplace=True)
df_food_col_subset

     calories_day                    weight  Gender
1             3.0                       155       1
2             4.0  I'm not answering this.        1
3             3.0             Not sure, 240       1
4             2.0                       190       1
5             3.0                       190       1
..            ...                       ...     ...
118           3.0                       140       1
119           3.0                       185       2
120           4.0                       156       1
121           2.0                       180       1
123           4.0                       135       2

[104 rows x 3 columns]

In [37]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂
df_food.isna().sum().to_frame()
#the original DataFrame, df_food, is unaffected by the in-place modifications made to df_food_col_subset. The NaN sums for the original DataFrame remain unchanged, indicating that the dropna operation on df_food_col_subset did not alter df_food.

                               0
GPA                            2
Gender                         0
breakfast                      0
calories_chicken               0
calories_day                  19
calories_scone                 1
coffee                         0
comfort_food                   1
comfort_food_reasons           2
comfort_food_reasons_coded    19
cook                           3
comfort_food_reasons_coded.1   0
cuisine                       17
diet_current                   1
diet_current_coded             0
drink                          2
eating_changes                 3
eating_changes_coded           0
eating_changes_coded1          0
eating_out                     0
employment                     9
ethnic_food                    0
exercise                      13
father_education               1
father_profession              3
fav_cuisine                    2
fav_cuisine_coded              0
fav_food                       2
food_childhood                 1
fries                          0
fruit_day                      0
grade_level                    0
greek_food                     0
healthy_feeling                0
healthy_meal                   1
ideal_diet                     1
ideal_diet_coded               0
income                         1
indian_food                    0
italian_food                   0
life_rewarding                 1
marital_status                 1
meals_dinner_friend            3
mother_education               3
mother_profession              2
nutritional_check              0
on_off_campus                  1
parents_cook                   0
pay_meal_out                   0
persian_food                   1
self_perception_weight         1
soup                           1
sports                         2
thai_food                      0
tortilla_calories              1
turkey_calories                0
type_sports                   26
veggies_day                    0
vitamins                       0
waffle_calories                0
weight                         2

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [44]:
# Fix that in-place.
# Fix that in-place.
df_food_col_subset["weight"] = pd.to_numeric(
    df_food_col_subset["weight"], errors="coerce"
)

df_food_col_subset.dropna(inplace=True)
df_food_col_subset

     calories_day  weight  Gender
1             3.0   155.0       1
4             2.0   190.0       1
5             3.0   190.0       1
6             3.0   180.0       2
7             3.0   137.0       1
..            ...     ...     ...
118           3.0   140.0       1
119           3.0   185.0       2
120           4.0   156.0       1
121           2.0   180.0       1
123           4.0   135.0       2

[101 rows x 3 columns]

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [48]:
# Savey save!

df_food_col_subset.to_csv("clean_food_data.csv", index=False)

In [ ]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [51]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.

salary_data_set_path = "../data/Ask A Manager Salary Survey 2021 (Responses).csv"
salary_data_set_path = "../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv"
df_salary = pd.read_csv(salary_data_set_path, sep="\t")

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [52]:
# Count by hand. I’m dead serious.
df_salary.shape

(28062, 18)

What are the columns and their types?

In [53]:
# Show the column names and their types.

df_salary.dtypes

Timestamp                                                                                                                                                                                                                                   str
How old are you?                                                                                                                                                                                                                            str
What industry do you work in?                                                                                                                                                                                                               str
Job title                                                                                                                                                                                                                                   str
If your job title needs additional context, please clarify here:                                                                                                                                                                            str
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)        str
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                          float64
Please indicate the currency                                                                                                                                                                                                                str
If "Other," please indicate the currency here:                                                                                                                                                                                              str
If your income needs additional context, please provide it here:                                                                                                                                                                            str
What country do you work in?                                                                                                                                                                                                                str
If you're in the U.S., what state do you work in?                                                                                                                                                                                           str
What city do you work in?                                                                                                                                                                                                                   str
How many years of professional work experience do you have overall?                                                                                                                                                                         str
How many years of professional work experience do you have in your field?                                                                                                                                                                   str
What is your highest level of education completed?                                                                                                                                                                                          str
What is your gender?                                                                                                                                                                                                                        str
What is your race? (Choose all that apply.)                                                                                                                                                                                                 str
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [55]:
# Rename ‘em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race
df_salary.columns = [
    "timestamp",
    "age",
    "industry",
    "title",
    "title_context",
    "salary",
    "additional_comp",
    "currency",
    "currency_other",
    "income_context",
    "country",
    "state",
    "city",
    "experience_overall",
    "experience_field",
    "education",
    "gender",
    "race"
]
df_salary.head()

,timestamp,age,industry,title,title_context,salary,additional_comp,currency,currency_other,income_context,country,state,city,experience_overall,experience_field,education,gender,race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [56]:
# List the unique industries and a count of their instances.

df_salary["industry"].value_counts()

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [57]:
# Filtery filter.

df_salary_tech = df_salary[df_salary["industry"] == "Computing or Tech"]

Do a sanity check by counting.

In [58]:
# Sanity check count.

df_salary_tech["industry"].value_counts()

industry
Computing or Tech    4699
Name: count, dtype: int64

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [59]:
# Filtery filter (in place) for just the jobs that pay in USD!

df_salary_tech.drop(
    df_salary_tech[df_salary_tech["currency"] != "USD"].index,
    inplace=True
)

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [61]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.

 df_salary_tech["country"].value_counts()

IndentationError: unexpected indent (373096530.py, line 3)

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [62]:
# Replace them all in-place with 'US'.

top_5 = df_salary_tech["country"].value_counts().head(5).index

df_salary_tech["country"].replace(top_5, "US", inplace=True)

/tmp/ipykernel_5348/2240602197.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_salary_tech["country"].replace(top_5, "US", inplace=True)

8           US
43          US
44          US
46          US
47          US
         ...
28044       US
28051      Usa
28052      Usa
28058       US
28060    Burma
Name: country, Length: 3777, dtype: str

Have a look at the count of each unique country again now.

In [63]:
# Count again.

df_salary_tech["country"].value_counts()

country
United States                1576
USA                          1222
US                            412
U.S.                          108
United States of America       90
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
U.S.                            2
United State of America         2
Unite States                    2
Australia                       2
UnitedStates                    2
India                           2
U.S                             2
Usa                             2
United States Of America        2
Spain                           2
Brazil                          2
United Kingdom                  2
united States                   2
New Zealand                     2
Poland                          2
France                          2
U.S.A                           2
United States of america        2
US                              1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
 US                             1
United State                    1
Cuba                            1
Danmark                         1
Italy                           1
International                   1
United Stated                   1
Remote (philippines)            1
Singapore                       1
Uruguay                         1
Mexico                          1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Netherlands                     1
China                           1
San Francisco                   1
Romania                         1
United STates                   1
Japan                           1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
Unites States                   1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Name: count, dtype: int64

Did you notice anything interesting?

In [64]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [ ]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [66]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.

df_salary_tech["salary"] = pd.to_numeric(
    df_salary_tech["salary"].astype(str).str.replace(",", "", regex=False),
    errors="coerce"
)

df_salary_tech.groupby("state")["salary"].agg(
    ["min", "mean", "max"]
).sort_values("mean", ascending=False)

                                   min           mean      max
state
Michigan, Texas, Washington     340000  340000.000000   340000
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
Georgia, Massachusetts          175000  175000.000000   175000
Florida                          28800  157457.232143  2600000
Alabama, District of Columbia   156000  156000.000000   156000
California                           0  154857.215478   875000
Washington                          72  151423.670588   950000
New York                         14000  148054.638968   590000
Nevada                           38000  141310.000000   425000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  135213.537954  1650000
District of Columbia             10000  132318.036364   267500
New Mexico                       70000  132200.000000   300000
Utah, Vermont                   130000  130000.000000   130000
New Jersey                       40000  128802.475000   603000
Connecticut                      62400  128375.000000   270000
Virginia                         43642  127706.355932   450000
Colorado                         45000  127240.006849   630000
Massachusetts, Rhode Island     125000  125000.000000   125000
Oregon                           16200  124297.800000   320000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  119268.242604   315000
Georgia                          29120  117893.098765   250000
Maryland                         51260  117862.370370   205000
Louisiana, Washington           117000  117000.000000   117000
Delaware                         63000  116600.000000   169000
South Dakota                     86000  115333.333333   150000
Wisconsin                            1  114268.000000   920000
Texas                            10700  113909.713004   280000
Tennessee                        36550  112847.058824   240000
Alaska                           67000  112500.000000   158000
Vermont                          65000  111781.250000   200000
Pennsylvania                     32000  111623.123894   237000
Idaho                            50000  111527.692308   312000
Rhode Island                     76000  111491.666667   180000
District of Columbia, Virginia  109200  109200.000000   109200
Minnesota                        34000  106752.793103   230000
Ohio                             32240  106338.835821   954000
Utah                             33280  105836.479167   245000
North Carolina                   29000  105035.441441   260000
New York, Texas                 105000  105000.000000   105000
Massachusetts, New Hampshire    105000  105000.000000   105000
Arizona                          35000  104491.891892   210000
Maine                            50000  103571.428571   173000
South Carolina                   40000  102111.111111   205000
Iowa                             47840   99729.736842   160000
Kansas                           41500   99565.052632   167000
North Dakota                     45760   97880.000000   150000
Michigan                         36800   96855.363636   235000
Montana                          65000   95500.000000   145000
Missouri                            80   95317.652174   200000
New Hampshire                       55   95179.705882   193000
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
Alabama                          29120   92510.000000   350000
Kentucky                         39000   92375.000000   170000
Nebraska                         43000   90975.294118   166400
Indiana                          15000   88566.647059   200000
Oklahoma                         28536   87929.500000   180000
Louisiana                        35360   83269.090909   150000
Massachusetts, Pennsylvania      83000   83000.000000    83000
California, Maryland             81500   81500.000000    81500
Arkansas                             4   74257.000000   144000
Alabama, Montana                 72000   72000.000000    72000

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [68]:
# Fix it in-place.

df_salary_tech.dropna(inplace=True)
df_salary_tech

,timestamp,age,industry,title,title_context,salary,additional_comp,currency,currency_other,income_context,country,state,city,experience_overall,experience_field,education,gender,race
28007,2/6/2024 21:15:28,18-24,Computing or Tech,sdsd,ds,4,22.0,USD,1,dd,ss,Arkansas,s,5-7 years,11 - 20 years,Some college,Man,Black or African American

Let’s try that again.

In [69]:
# Try it again. Yeah!

df_salary_tech.groupby("state")["salary"].agg(["min", "mean", "max"]).sort_values("mean", ascending=False)

          min  mean  max
state
Arkansas    4   4.0    4

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [70]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.

df_salary_tech["timestamp"] = pd.to_datetime(df_salary_tech["timestamp"])

df_salary_recent = df_salary_tech[
    df_salary_tech["timestamp"].dt.year.isin([2021, 2022, 2023])
]

df_salary_recent

Empty DataFrame
Columns: [timestamp, age, industry, title, title_context, salary, additional_comp, currency, currency_other, income_context, country, state, city, experience_overall, experience_field, education, gender, race]
Index: []

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)